<?php

/**
 * Created by PhpStorm.
 * User: SABER KHALIFA
 * Date: 20/10/2016
 * Time: 09:41
 */
class AdministrateurRepository extends MarketRepository
{
    /**
     * THE ROLE OF THIS METHOD IS TO INSERT NEW ADMINISTRATEUR
     * @param Administrateur $administrateur
     */
    public function persist(Administrateur $administrateur)
    {
        parent::save($administrateur); // TODO: Change the autogenerated stub
    }

    /**
     * THE ROLE OF THIS METHOD IS TO UPDATE  ADMINISTRATEUR
     * @param Administrateur $administrateur
     */
    public function merge(Administrateur $administrateur)
    {
        parent::update($administrateur);
    }

    /**
     *  THE ROLE OF THIS METHOD IS TO DELETE  ADMINISTRATEUR FROM THE TABLE
     * @param $object
     */
    public function remove($object)
    {
        parent::delete($object); // TODO: Change the autogenerated stub
    }

    /**
     * THE ROLE OF THIS METHOD IS TO GET ALL ADMINISTRATEUR
     * @return array
     */
    public function getAll()
    {
        $data = array();
        $rs = parent::findAll(array("name" => "Administrateur"));
        foreach ($rs as $k => $v) {
            foreach ($v as $vi) {
                $data[$k] = new Administrateur($v['ID'],$v['IDENTIFIANT'],$v['MOTPASSE']);
            }
        }
        return $data;
    }
    /**
     * THE ROLE OF THIS METHOD IS TO FIND  ADMINISTRATEUR BY ID
     * @param $value
     * @return array
     */
    public function getOne($value)
    {
        $data = array();
        $rs = parent::findOne(array("name" => "Administrateur", "id" => "ID", "value" => $value));
        foreach ($rs as $k => $v) {
            foreach ($v as $vi) {
                $data[$k] =  new Administrateur($v['ID'],$v['IDENTIFIANT'],$v['MOTPASSE']);
            }
        }
        var_dump($data);
        return $data;
    }
}