<?php

/**
 * Created by PhpStorm.
 * User: SABER KHALIFA
 * Date: 20/10/2016
 * Time: 09:41
 */
class CategorieRepository extends MarketRepository
{
    /**
     * THE ROLE OF THIS METHOD IS TO INSERT NEW CATEGORIE
     * @param Categorie $categorie
     */
    public function persist(Categorie $categorie)
    {
        parent::save($categorie); // TODO: Change the autogenerated stub
    }

    /**
     * THE ROLE OF THIS METHOD IS TO UPDATE  CATEGORIE
     * @param Categorie $categorie
     */
    public function merge(Categorie $categorie)
    {
        parent::update($categorie);
    }

    /**
     *  THE ROLE OF THIS METHOD IS TO DELETE  CATEGORIE FROM THE TABLE
     * @param $object
     */
    public function remove($object)
    {
        parent::delete($object); // TODO: Change the autogenerated stub
    }

    /**
     * THE ROLE OF THIS METHOD IS TO GET ALL CATEGORIE
     * @return array
     */
    public function getAll()
    {
        $data = array();
        $rs = parent::findAll(array("name" => "Categorie"));
        foreach ($rs as $k => $v) {
            foreach ($v as $vi) {
                $data[$k] = new Categorie($v['ID'], $v['SUPER_CATEG'], $v['NOM']);
            }
        }

        return $data;
    }

    /**
     * THE ROLE OF THIS METHOD IS TO FIND  CATEGORIE BY ID
     * @param $value
     * @return array
     */
    public function getOne($value)
    {
        $data = array();
        $rs = parent::findOne(array("name" => "Categorie", "id" => "ID", "value" => $value));
        foreach ($rs as $k => $v) {
            foreach ($v as $vi) {
                $data[$k] = new Categorie($v['ID'], $v['SUPER_CATEG'], $v['NOM']);
            }
        }
        return $data;
    }
}