<?php

/**
 * Created by PhpStorm.
 * User: SABER KHALIFA
 * Date: 20/10/2016
 * Time: 09:41
 */
class ClientRepository extends MarketRepository
{

    /**
     * THE ROLE OF THIS METHOD IS TO INSERT NEW CLIENT
     * @param Client $client
     */
    public function persist(Client $client)
    {
        parent::save($client); // TODO: Change the autogenerated stub
    }

    /**
     * THE ROLE OF THIS METHOD IS TO UPDATE  CLIENT
     * @param Client $client
     */
    public function merge(Client $client)
    {
        parent::update($client);
    }

    /**
     *  THE ROLE OF THIS METHOD IS TO DELETE  CLIENT FROM THE TABLE
     * @param $object
     */
    public function remove($object)
    {
        parent::delete($object); // TODO: Change the autogenerated stub
    }

    /**
     * THE ROLE OF THIS METHOD IS TO GET ALL CLIENT
     * @return array
     */
    public function getAll()
    {
        $data = array();
        $rs = parent::findAll(array("name" => "Client"));
        foreach ($rs as $k => $v) {
            foreach ($v as $vi) {
                $data[$k] = new Client($v['CLIENTID'],$v['NOM'],$v['EMAIL'],$v['MOTPASSE']);
            }
        }
        return $data;
    }
    /**
     * THE ROLE OF THIS METHOD IS TO FIND  CLIENT BY ID
     * @param $value
     * @return array
     */
    public function getOne($value)
    {
        $data = array();
        $rs = parent::findOne(array("name" => "Client", "id" => "CLIENTID", "value" => $value));
        foreach ($rs as $k => $v) {
            foreach ($v as $vi) {
                $data[$k] = new Client($v['CLIENTID'],$v['NOM'],$v['EMAIL'],$v['MOTPASSE']);
            }
        }
        return $data;
    }
}