<?php
/**
 * Created by PhpStorm.
 * User: SABER KHALIFA
 * Date: 20/10/2016
 * Time: 09:41
 */
class CommandeRepository extends MarketRepository
{
    /**
     * THE ROLE OF THIS METHOD IS TO INSERT NEW COMMANDE
     * @param Commande $commande
     */
    public function persist(Commande $commande)
    {
        parent::save($commande); // TODO: Change the autogenerated stub
    }
    /**
     * THE ROLE OF THIS METHOD IS TO UPDATE  COMMANDE
     * @param Commande $commande
     */
    public function merge(Commande $commande)
    {
        parent::update($commande);
    }
    /**
     *  THE ROLE OF THIS METHOD IS TO DELETE  COMMANDE FROM THE TABLE
     * @param $object
     */
    public function remove($object)
    {
        parent::delete($object); // TODO: Change the autogenerated stub
    }
    /**
     * THE ROLE OF THIS METHOD IS TO GET ALL COMMANDE
     * @return array
     */
    public function getAll()
    {
        $data = array();
        $rs = parent::findAll(array("name" => "Commande"));
        foreach ($rs as $k => $v) {
            foreach ($v as $vi) {
                $data[$k] = new Commande($v['ID'],$v['CLIENTID'],$v['PRODID'],$v['NBPRODUITS'],$v['DATEAJOUT']);
            }
        }
        return $data;
    }
    /**
     * THE ROLE OF THIS METHOD IS TO FIND  COMMANDE BY ID
     * @param $value
     * @return array
     */
    public function getOne($value)
    {
        $data = array();
        $rs = parent::findOne(array("name" => "Commande","id"=>"CLIENTID","value"=>$value));
        foreach ($rs as $k => $v) {
            foreach ($v as $vi) {
                $data[$k] =  new Commande($v['ID'],$v['CLIENTID'],$v['PRODID'],$v['NBPRODUITS'],$v['DATEAJOUT']);
            }
        }
        return $data;
    }
}