<?php

/**
 * Created by PhpStorm.
 * User: SABER KHALIFA
 * Date: 20/10/2016
 * Time: 09:41
 */
class ContactRepository extends MarketRepository
{
    /**
     * THE ROLE OF THIS METHOD IS TO INSERT NEW CONTACT
     * @param Contact $contact
     */
    public function persist(Contact $contact)
    {
        parent::save($contact); // TODO: Change the autogenerated stub
    }

    /**
     * THE ROLE OF THIS METHOD IS TO UPDATE  CONTACT
     * @param Contact $contact
     */
    public function merge(Contact $contact)
    {
        parent::update($contact);
    }

    /**
     *  THE ROLE OF THIS METHOD IS TO DELETE  CONTACT FROM THE TABLE
     * @param $object
     */
    public function remove($object)
    {
        parent::delete($object); // TODO: Change the autogenerated stub
    }

    /**
     * THE ROLE OF THIS METHOD IS TO GET ALL CONTACT
     * @return array
     */
    public function getAll()
    {
        $data = array();
        $rs = parent::findAll(array("name" => "Contact"));
        foreach ($rs as $k => $v) {
            foreach ($v as $vi) {
                $data[$k] = new Contact($v['ID'],$v['NOM'],$v['EMAIL'],$v['OBJET'],$v['MESSAGE']);
            }
        }
        return $data;
    }
    /**
     * THE ROLE OF THIS METHOD IS TO FIND  CONTACT BY ID
     * @param $value
     * @return array
     */
    public function getOne($value)
    {
        $data = array();
        $rs = parent::findOne(array("name" => "Contact","id"=>"ID","value"=>$value));
        foreach ($rs as $k => $v) {
            foreach ($v as $vi) {
                $data[$k] = new Contact($v['ID'],$v['NOM'],$v['EMAIL'],$v['OBJET'],$v['MESSAGE']);
            }
        }
        return $data;
    }
}