<?php

/**
 * Created by PhpStorm.
 * User: SABER KHALIFA
 * Date: 20/10/2016
 * Time: 09:41
 */
class ImageRepository extends MarketRepository
{
    /**
     * THE ROLE OF THIS METHOD IS TO INSERT NEW IMAGE
     * @param Image $image
     */
    public function persist(Image $image)
    {
        parent::save($image); // TODO: Change the autogenerated stub
    }

    /**
     * THE ROLE OF THIS METHOD IS TO UPDATE  IMAGE
     * @param Image $image
     */
    public function merge(Image $image)
    {
        parent::update($image);
    }

    /**
     *  THE ROLE OF THIS METHOD IS TO DELETE  IMAGE FROM THE TABLE
     * @param $object
     */
    public function remove($object)
    {
        parent::delete($object); // TODO: Change the autogenerated stub
    }

    /**
     * THE ROLE OF THIS METHOD IS TO GET ALL IMAGE
     * @return array
     */
    public function getAll()
    {
        $data = array();
        $rs = parent::findAll(array("name" => "Image"));
        foreach ($rs as $k => $v) {
            foreach ($v as $vi) {
                $data[$k] = new Image($v['id'], $v['name'], $v['produitID']);
            }
        }
        return $data;
    }

    /**
     * THE ROLE OF THIS METHOD IS TO FIND  IMAGE BY ID
     * @param $value
     * @return array
     */
    public function getOne($value)
    {
        $data = array();
        $rs = parent::findOne(array("name" => "Image", "id" => "id", "value" => $value));
        foreach ($rs as $k => $v) {
            foreach ($v as $vi) {
                $data[$k] = new Image($v['id'], $v['name'], $v['produitID']);
            }
        }
        return $data;
    }
}